// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [{
      type: 'autogenerated',
      dirName: 'tutorial-basics',
    },
  ],
},
{
  type: 'category',
  label: 'Tutorial - Extras',
  items: [
    {
      type: 'autogenerated',
      dirName: 'tutorial-extras',
    },
  ],
},
{
  type: 'category',
  label: 'Kobra S1 Combo',
  items: [
    {
      type: 'autogenerated',
      dirName: 'anycubic',
    },
  ],
},
  ],
};

module.exports = sidebars;
